// This file will be auto-generated by: npx supabase gen types typescript
// For now, manually define the types we know about.
// Regenerate after each database migration.

export interface Database {
	public: {
		Tables: {
			employees: {
				Row: {
					id: string;
					name: string;
					email: string;
					role: string;
					created_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					email: string;
					role: string;
					created_at?: string;
				};
				Update: {
					name?: string;
					email?: string;
					role?: string;
				};
			};
			customers: {
				Row: {
					id: string;
					name: string;
					contact_name: string | null;
					email: string | null;
					phone: string | null;
					abn: string | null;
					payment_terms: number;
					notes: string | null;
					billing_street: string | null;
					billing_city: string | null;
					billing_state: string | null;
					billing_postcode: string | null;
					billing_country: string | null;
					shipping_street: string | null;
					shipping_city: string | null;
					shipping_state: string | null;
					shipping_postcode: string | null;
					shipping_country: string | null;
					is_active: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					contact_name?: string | null;
					email?: string | null;
					phone?: string | null;
					abn?: string | null;
					payment_terms?: number;
					notes?: string | null;
					billing_street?: string | null;
					billing_city?: string | null;
					billing_state?: string | null;
					billing_postcode?: string | null;
					billing_country?: string | null;
					shipping_street?: string | null;
					shipping_city?: string | null;
					shipping_state?: string | null;
					shipping_postcode?: string | null;
					shipping_country?: string | null;
					is_active?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					name?: string;
					contact_name?: string | null;
					email?: string | null;
					phone?: string | null;
					abn?: string | null;
					payment_terms?: number;
					notes?: string | null;
					billing_street?: string | null;
					billing_city?: string | null;
					billing_state?: string | null;
					billing_postcode?: string | null;
					billing_country?: string | null;
					shipping_street?: string | null;
					shipping_city?: string | null;
					shipping_state?: string | null;
					shipping_postcode?: string | null;
					shipping_country?: string | null;
					is_active?: boolean;
				};
			};
			invoices: {
				Row: {
					id: string;
					customer_id: string;
					invoice_number: string | null;
					status: string;
					issue_date: string;
					due_date: string;
					reference: string | null;
					notes: string | null;
					internal_notes: string | null;
					payment_terms: string | null;
					subtotal: number;
					tax_total: number;
					total: number;
					amount_paid: number;
					amount_due: number;
					sent_at: string | null;
					paid_at: string | null;
					is_archived: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					customer_id: string;
					invoice_number?: string | null;
					status?: string;
					issue_date?: string;
					due_date: string;
					reference?: string | null;
					notes?: string | null;
					internal_notes?: string | null;
					payment_terms?: string | null;
					subtotal?: number;
					tax_total?: number;
					total?: number;
					amount_paid?: number;
					amount_due?: number;
				};
				Update: {
					customer_id?: string;
					invoice_number?: string | null;
					status?: string;
					issue_date?: string;
					due_date?: string;
					reference?: string | null;
					notes?: string | null;
					internal_notes?: string | null;
					payment_terms?: string | null;
					subtotal?: number;
					tax_total?: number;
					total?: number;
					amount_paid?: number;
					amount_due?: number;
				};
			};
			line_items: {
				Row: {
					id: string;
					invoice_id: string | null;
					quote_id: string | null;
					description: string;
					quantity: number;
					unit_price: number;
					discount_percent: number;
					tax_rate_id: string | null;
					tax_name: string | null;
					tax_rate: number;
					tax_amount: number;
					line_total: number;
					sort_order: number;
					created_at: string;
				};
				Insert: {
					id?: string;
					invoice_id?: string | null;
					quote_id?: string | null;
					description: string;
					quantity?: number;
					unit_price: number;
					discount_percent?: number;
					tax_rate_id?: string | null;
					tax_name?: string | null;
					tax_rate?: number;
					tax_amount?: number;
					line_total?: number;
					sort_order?: number;
				};
				Update: {
					description?: string;
					quantity?: number;
					unit_price?: number;
					discount_percent?: number;
					tax_rate_id?: string | null;
					tax_name?: string | null;
					tax_rate?: number;
					tax_amount?: number;
					line_total?: number;
					sort_order?: number;
				};
			};
			tax_rates: {
				Row: {
					id: string;
					name: string;
					rate: number;
					description: string | null;
					is_default: boolean;
					is_active: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					name: string;
					rate: number;
					description?: string | null;
					is_default?: boolean;
					is_active?: boolean;
				};
				Update: {
					name?: string;
					rate?: number;
					description?: string | null;
					is_default?: boolean;
					is_active?: boolean;
				};
			};
			document_settings: {
				Row: {
					id: string;
					company_name: string | null;
					company_email: string | null;
					company_phone: string | null;
					company_abn: string | null;
					company_logo_url: string | null;
					address_line1: string | null;
					address_city: string | null;
					address_state: string | null;
					address_postcode: string | null;
					address_country: string | null;
					default_payment_terms: number;
					default_notes: string | null;
					default_terms: string | null;
					default_footer: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					company_name?: string | null;
					company_email?: string | null;
					company_phone?: string | null;
					company_abn?: string | null;
					company_logo_url?: string | null;
					address_line1?: string | null;
					address_city?: string | null;
					address_state?: string | null;
					address_postcode?: string | null;
					address_country?: string | null;
					default_payment_terms?: number;
					default_notes?: string | null;
					default_terms?: string | null;
					default_footer?: string | null;
				};
				Update: {
					company_name?: string | null;
					company_email?: string | null;
					company_phone?: string | null;
					company_abn?: string | null;
					company_logo_url?: string | null;
					address_line1?: string | null;
					address_city?: string | null;
					address_state?: string | null;
					address_postcode?: string | null;
					address_country?: string | null;
					default_payment_terms?: number;
					default_notes?: string | null;
					default_terms?: string | null;
					default_footer?: string | null;
				};
			};
			number_sequences: {
				Row: {
					id: string;
					type: string;
					prefix: string;
					next_number: number;
					padding: number;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					type: string;
					prefix?: string;
					next_number?: number;
					padding?: number;
				};
				Update: {
					prefix?: string;
					next_number?: number;
					padding?: number;
				};
			};
		};
	};
}

// Helper types for easy access
export type Tables<T extends keyof Database['public']['Tables']> =
	Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
	Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
	Database['public']['Tables'][T]['Update'];
